version: '2'
services:
  app:
    image: drupal
    ports:
      - '8085:80'
    volumes:
      - ./drupal-7.56:/var/www/html
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root